#r "../../../packages/FParsec/lib/net40-client/FParsecCS.dll" 
#r "../../../packages/System.Collections.Immutable/lib/netstandard1.0/System.Collections.Immutable.dll" 
#r "../../../packages/System.ValueTuple/lib/netstandard1.0/System.ValueTuple.dll" 
#r "../../../packages/FParsec/lib/net40-client/FParsec.dll" 
printfn "Loaded group Main" 